services:
    server1yehan:
      image: docker.iesquevedo.es/yehan.xue/practica1/server1
      hostname: server1yehan
      privileged: true
      entrypoint: ["sh", "-c","netfilter-persistent start && ip route replace default via 192.168.2.11 && ip route add 192.168.3.0 via 192.168.2.11 && /usr/sbin/sshd -D"]
      networks:
        redPrincipal_yehan:
          ipv4_address: 192.168.1.10
        redServidor_yehan:
          ipv4_address: 192.168.2.10
    server2yehan:
      image: docker.iesquevedo.es/yehan.xue/practica1/server2
      hostname: server2yehan
      privileged: true
      entrypoint: ["sh", "-c","netfilter-persistent start && ip route replace default via 192.168.2.10 && ip route add 192.168.1.0 via 192.168.2.10 && /usr/sbin/sshd -D"]
      networks:
        redServidor_yehan:
          ipv4_address: 192.168.2.11
        redDestino_yehan:
          ipv4_address: 192.168.3.10
  
  
    cliente1yehan:
      image: docker.iesquevedo.es/yehan.xue/practica1/cliente1
      hostname: cliente1yehan
      privileged: true
      entrypoint: ["sh", "-c","ip route replace default via 192.168.1.10 && /usr/sbin/sshd -D"]
      networks:
        redPrincipal_yehan:
          ipv4_address: 192.168.1.11
    cliente2yehan:
      image: docker.iesquevedo.es/yehan.xue/practica1/cliente2
      hostname: cliente2yehan
      privileged: true
      entrypoint: ["sh", "-c","ip route replace default via 192.168.3.10 && /usr/sbin/sshd -D"]

      networks:
        redDestino_yehan:
          ipv4_address: 192.168.3.11
  
    
  
  
  
  
networks:
    
    redPrincipal_yehan:
      name: redPrincipal_yehan
      ipam:
        config:
          - subnet: "192.168.1.0/24"
            ip_range: "192.168.1.64/32"
            gateway: "192.168.1.1"
    redServidor_yehan:
      name: redServidor_yehan
      ipam:
        config:
          - subnet: "192.168.2.0/24"
            ip_range: "192.168.2.64/32"
            gateway: "192.168.2.1"
    redDestino_yehan:
      name: redDestino_yehan
      ipam:
        config:
          - subnet: "192.168.3.0/24"
            ip_range: "192.168.3.64/32"
            gateway: "192.168.3.1"
    