services:

  clientesalida:
    image: yehan2002/ubuntu-ssh
    hostname: clientesalida
    privileged: true
    entrypoint: ["sh","-c"," ip route replace default via 192.168.101.2 && /usr/sbin/sshd -D"]
    networks:
      red_salida:
        ipv4_address: 192.168.101.10  # Dentro del rango de red_salida

  clientedepartamento1:
    image: yehan2002/ubuntu-ssh
    hostname: clientedepartamento1
    privileged: true
    entrypoint: ["sh", "-c"," ip route replace default via 192.168.102.2 && /usr/sbin/sshd -D"]
    networks:
      red_departamento:
        ipv4_address: 192.168.102.10  # Dentro del rango de red_departamento

  clientedepartamento2:
    image: yehan2002/ubuntu-ssh
    hostname: clientedepartamento2
    privileged: true
    entrypoint: ["sh", "-c"," ip route replace default via 192.168.102.2 && /usr/sbin/sshd -D"]
    networks:
      red_departamento:
        ipv4_address: 192.168.102.11  # Dentro del rango de red_departamento

  clientejefe:
    image: yehan2002/ubuntu-ssh
    hostname: clientejefe
    privileged: true
    entrypoint: ["sh", "-c"," ip route replace default via 192.168.103.2 && /usr/sbin/sshd -D"]
    networks:
      red_jefe:
        ipv4_address: 192.168.103.10  # Dentro del rango de red_jefe

  clientewifi:
    image: yehan2002/ubuntu-ssh
    hostname: clientewifi
    privileged: true
    entrypoint: ["sh", "-c"," ip route replace default via 192.168.104.2 && /usr/sbin/sshd -D"]
    networks:
      red_wifi:
        ipv4_address: 192.168.104.10  # Dentro del rango de red_wifi


# route


  routesalida:
    image: yehan2002/ubuntu-ssh
    hostname: routesalida
    privileged: true
    entrypoint: ["sh", "-c"," ip route replace default via 192.168.100.1 &&  ip route add 192.168.102.0/24 via 192.168.101.3 &&  ip route add 192.168.103.0/24 via 192.168.101.4 &&  ip route add 192.168.104.0/24 via 192.168.101.5 && /usr/sbin/sshd -D"]
    networks:
      red_internet:
        ipv4_address: 192.168.100.2  # Dentro del rango de red_internet
      red_salida:
        ipv4_address: 192.168.101.2  # Dentro del rango de red_salida

  routedepartamento:
    image: yehan2002/ubuntu-ssh
    hostname: routedepartamento
    privileged: true
    entrypoint: ["sh", "-c","ip route replace default via 192.168.101.2 && /usr/sbin/sshd -D"]
    networks:
      red_salida:
        ipv4_address: 192.168.101.3  # Dentro del rango de red_salida
      red_departamento:
        ipv4_address: 192.168.102.2  # Dentro del rango de red_departamento

  routejefe:
    image: yehan2002/ubuntu-ssh
    hostname: routejefe
    privileged: true
    entrypoint: ["sh", "-c","ip route replace default via 192.168.101.2 && /usr/sbin/sshd -D"]
    networks:
      red_salida:
        ipv4_address: 192.168.101.4  # Dentro del rango de red_salida
      red_jefe:
        ipv4_address: 192.168.103.2  # Dentro del rango de red_jefe

  routewifi:
    image: yehan2002/ubuntu-ssh
    hostname: routewifi
    privileged: true
    entrypoint: ["sh", "-c","ip route replace default via 192.168.101.2 && /usr/sbin/sshd -D"]
    networks:
      red_salida:
        ipv4_address: 192.168.101.5  # Dentro del rango de red_salida
      red_wifi:
        ipv4_address: 192.168.104.2  # Dentro del rango de red_wifi

networks:
  red_internet:
    name: red_internet
    ipam:
      config:
        - subnet: "192.168.100.0/24"       
          ip_range: "192.168.100.255/32"
          gateway: "192.168.100.1"

  red_salida:
    name: red_salida
    ipam:
      config:
        - subnet: "192.168.101.0/24"       
          ip_range: "192.168.101.255/32"
          gateway: "192.168.101.1"

  red_departamento:
    name: red_departamento
    ipam:
      config:
        - subnet: "192.168.102.0/24"       
          ip_range: "192.168.102.255/32"
          gateway: "192.168.102.1"

  red_jefe:
    name: red_jefe
    ipam:
      config:
        - subnet: "192.168.103.0/24"       
          ip_range: "192.168.103.255/32"
          gateway: "192.168.103.1"

  red_wifi:
    name: red_wifi
    ipam:
      config:
        - subnet: "192.168.104.0/24"       
          ip_range: "192.168.104.255/32"
          gateway: "192.168.104.1"
