services:

    clientesalida:
      image: docker.iesquevedo.es/yehan.xue/iptablescontodo1/clientesalida
      hostname: clientesalida
      privileged: true
      entrypoint: ["sh","-c"," ip route replace default via 192.168.101.2 && /usr/sbin/sshd -D"]
      networks:
        red_salida:
          ipv4_address: 192.168.101.10  

    clientedepartamento1:
      image: docker.iesquevedo.es/yehan.xue/iptablescontodo1/clientedepartamento1
      hostname: clientedepartamento1
      privileged: true
      entrypoint: ["sh", "-c"," ip route replace default via 192.168.102.2 && /usr/sbin/sshd -D"]
      networks:
        red_departamento:
          ipv4_address: 192.168.102.10  
    clientedepartamento2:
      image: docker.iesquevedo.es/yehan.xue/iptablescontodo1/clientedepartamento2
      hostname: clientedepartamento2
      privileged: true
      entrypoint: ["sh", "-c"," ip route replace default via 192.168.102.2 && /usr/sbin/sshd -D"]
      networks:
        red_departamento:
          ipv4_address: 192.168.102.11 

    clientejefe:
      image: docker.iesquevedo.es/yehan.xue/iptablescontodo1/clientejefe
      hostname: clientejefe
      privileged: true
      entrypoint: ["sh", "-c"," ip route replace default via 192.168.103.2 && /usr/sbin/sshd -D"]
      networks:
        red_jefe:
          ipv4_address: 192.168.103.10  

    clientewifi:
      image: docker.iesquevedo.es/yehan.xue/iptablescontodo1/clientewifi
      hostname: clientewifi
      privileged: true
      entrypoint: ["sh", "-c"," ip route replace default via 192.168.104.2 && /usr/sbin/sshd -D"]
      networks:
        red_wifi:
          ipv4_address: 192.168.104.10 

    routesalida:
      image: docker.iesquevedo.es/yehan.xue/iptablescontodo1/routesalida
      hostname: routesalida
      privileged: true
      entrypoint: ["sh", "-c","netfilter-persistent start && ip route replace default via 192.168.100.1 &&  ip route add 192.168.102.0/24 via 192.168.101.3 &&  ip route add 192.168.103.0/24 via 192.168.101.4 &&  ip route add 192.168.104.0/24 via 192.168.101.5 && /usr/sbin/sshd -D"]
      networks:
        red_internet:
          ipv4_address: 192.168.100.2  
        red_salida:
          ipv4_address: 192.168.101.2  

    routedepartamento:
      image: docker.iesquevedo.es/yehan.xue/iptablescontodo1/routedepartamento
      hostname: routedepartamento
      privileged: true
      entrypoint: ["sh", "-c","netfilter-persistent start && ip route replace default via 192.168.101.2 && /usr/sbin/sshd -D"]
      networks:
        red_salida:
          ipv4_address: 192.168.101.3  
        red_departamento:
          ipv4_address: 192.168.102.2  

    routejefe:
      image: docker.iesquevedo.es/yehan.xue/iptablescontodo1/routejefe
      hostname: routejefe
      privileged: true
      entrypoint: ["sh", "-c","netfilter-persistent start && ip route replace default via 192.168.101.2 && /usr/sbin/sshd -D"]
      networks:
        red_salida:
          ipv4_address: 192.168.101.4  
        red_jefe:
          ipv4_address: 192.168.103.2  

    routewifi:
      image: docker.iesquevedo.es/yehan.xue/iptablescontodo1/routewifi
      hostname: routewifi
      privileged: true
      entrypoint: ["sh", "-c","netfilter-persistent start && ip route replace default via 192.168.101.2 && /usr/sbin/sshd -D"]
      networks:
        red_salida:
          ipv4_address: 192.168.101.5  
        red_wifi:
          ipv4_address: 192.168.104.2 

networks:
    red_internet:
      name: red_internet
      ipam:
        config:
          - subnet: "192.168.100.0/24"       
            ip_range: "192.168.100.255/32"
            gateway: "192.168.100.1"

    red_salida:
      name: red_salida
      ipam:
        config:
          - subnet: "192.168.101.0/24"       
            ip_range: "192.168.101.255/32"
            gateway: "192.168.101.1"

    red_departamento:
      name: red_departamento
      ipam:
        config:
          - subnet: "192.168.102.0/24"       
            ip_range: "192.168.102.255/32"
            gateway: "192.168.102.1"

    red_jefe:
      name: red_jefe
      ipam:
        config:
          - subnet: "192.168.103.0/24"       
            ip_range: "192.168.103.255/32"
            gateway: "192.168.103.1"

    red_wifi:
      name: red_wifi
      ipam:
        config:
          - subnet: "192.168.104.0/24"       
            ip_range: "192.168.104.255/32"
            gateway: "192.168.104.1"
